spring:
  application:
    name: google_places_mcp_server

  main:
    web-application-type: none # stdio mode — no HTTP server needed

  ai:
    mcp:
      server:
        name: google-places-mcp-server
        version: 1.0.0
        type: SYNC
        stdio: true # enables stdio transport

google:
  places:
    baseUrl: https://maps.googleapis.com/maps/api/place
    header:
      key: X-Goog-Api-Key
    apiKey: ${GOOGLE_PLACES_API_KEY:} # expects GOOGLE_PLACES_API_KEY env variable to be set
